[tasks.submodule-init]
run = "git submodule update --init --recursive"

[tasks.make-build-folder]
run = "mkdir -p ReacomaExtension/build"
hide = true

[tasks.setupide]
description = "Extracts the compile_commands.json from CMake for the clangd server"
run = "cmake .. -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=1 && mv compile_commands.json ../../"
dir = "ReacomaExtension/build"
depends = ["make-build-folder"]

[tasks.configure]
run = "cmake .. -GNinja -DCMAKE_BUILD_TYPE={{arg(name='build_type', var=true)}} -DDEPLOYMENT_BUILD=OFF"
dir = "ReacomaExtension/build"
depends = ["make-build-folder"]

[tasks.configure-deployment]
run = "cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DDEPLOYMENT_BUILD=ON"
dir = "ReacomaExtension/build"
depends = ["make-build-folder"]

[tasks.build]
run = "ninja"
dir = "ReacomaExtension/build"

[tasks.deploy]
description = "Configures, builds, and finalizes the deployment build."
run = [
  "{{mise_bin}} run tests",
  "{{mise_bin}} run configure-deployment",
  "{{mise_bin}} run build",
  "echo done!"
]

[tasks.clean]
run = "rm -rf ReacomaExtension/build/*"

[tasks.make-build-folder-windows]
run = '''pwsh -Command "New-Item -Path 'ReacomaExtension/build' -ItemType Directory -Force"'''
hide = true

[tasks.configure-deployment-windows]
run = "cmake -S ReacomaExtension -B ReacomaExtension/build -GNinja -DCMAKE_BUILD_TYPE=Release -DDEPLOYMENT_BUILD=ON"
depends = ["make-build-folder-windows"]

[tasks.build-windows] # Renamed for clarity
run = "cmake --build ReacomaExtension/build --config Release"

[tasks.tests-windows]
description = "Configures (Release), builds, and runs the algorithm tests on Windows"
run = [
  "mise run configure-deployment-windows",
  "cmake --build ReacomaExtension/build --config Release --target ReacomaTests",
  "pwsh -Command \"cd ReacomaExtension/build; ./ReacomaTests.exe\""
]

[tasks.deploy-windows]
description = "Configures and builds for Windows."
run = [
  "mise run tests-windows",
  "mise run configure-deployment-windows",
  "mise run build-windows",
]

[tasks.clean-windows]
run = '''pwsh -Command "if (Test-Path 'ReacomaExtension/build') { Remove-Item -Path 'ReacomaExtension/build' -Recurse -Force }"'''

[tasks.tests]
description = "Configures (Release), builds, and runs the algorithm tests"
run = [
  "mise run configure Release",
  "ninja ReacomaTests",
  "./ReacomaTests"
]
dir = "ReacomaExtension/build"
depends = ["make-build-folder"]
